### ISSUE TITLE
Installation Issue "Setting current slot to 'a" Failed"

### ISSUE THREAD

**Issue by Corey68** [AOSPAlliance/device-flasher#11]
I have gone through and "manually" tried to install it and used the auto installer and the same message appears.  I am new to all of this, but I think it has to do with an update to android 11.  I am not sure.  Under the "fastboot tooling changes" there are things that refer to measures put in place to prevent from bricking the phone.

The exact error it posted as 
Setting current slot to 'a'                        FAILED (remote: 'Changing slot with snapshot applied may cancel the update.')

https://source.android.com/devices/tech/ota/virtual_ab/implement#fastboot-tooling-changes

**Comment by Uldiniad** [comment]
I'm guessing you hit this issue on a 4a (sunfish). I think you're right that this is an Android version related issue. I did not hit this but did allow the phone to get the latest updates before attempting to use the flasher to flash the calyx image. I think this issue will not be present when CalyxOS 11 is released given that there won't be a version downgrade factor. Keeping the issue open in the meantime

**Comment by Corey68** [comment]
Yes, it is an issue on the 4a(Sunfish).  Any idea when Calyxos 11 would be out?  I bought the phone specifically with the intent to put Calyxos on the phone.

**Comment by Corey68** [comment]
I did allow the latest updates before using the flasher as well.

**Comment by Uldiniad** [comment]
the flasher should have worked then. it did for me. either way you can check what they did here https://www.reddit.com/r/CalyxOS/comments/jlx95g/pixel_4a_installation_issues_boot_slot/gas0hvw?utm_source=share&utm_medium=web2x&context=3
see if that solves this issue for you

concerning CalyxOS 11, it is actively being worked on. I cannot give an ETA

**Comment by Corey68** [comment]
YES THIS WORKED!!!!  

I was looking forever and never found that thread.  Thank you!

**Comment by Corey68** [comment]
In case anyone was wondering.  I went through platform tools and used the command below.  It now installs!!!

./fastboot snapshot-update cancel
