### ISSUE TITLE
kind plea from visually impaired user where to get .zip firmware

### ISSUE THREAD

**Issue by JanuszChmiel** [AOSPAlliance/device-flasher#16]
Dear specialists,
Please, is it also possible to use yours tool to flash Samsung ANdroid phones? Please, who of us would know where to find The firmware for Samsung Galaxy chat GTB5330 with firmware which have been made for Czech Republic and for our mobile operators. T-mobile, O2 and Wodaphone?
Or this tool is not intended to be used with Samsung mobile devices?

I have found out, that this old but light weight mobile phone with build in compas and good GPS receiever is ideal for navigation in The terain. BUt I have experimented with it several years ago. And powerful New kingroot app have brought very unpleasant experience to  Me. It is sad if there is no tool to reflash my phone to its original state again.
I have found The firmware, but it is not compressed in .zip format. It is compressed by using tar.md5.
Any advice will be very welcomed.

**Comment by Uldiniad** [comment]
This tool can only work with devices that follow a specific flashing flow. Samsung has a quite particular setup and, as far as I can tell, we cannot support it.
You're aware of Heimdall/Odin?
