### ISSUE TITLE
When downloading the .exe I keep getting file contains a virus or malware

### ISSUE THREAD

**Issue by ghost** [AOSPAlliance/device-flasher#17]
I've never had this happen in the past with downloads.

Is this something I should be concerned about, is there some steps I should take, or is this a common occurrence for downloads here?

I need this flashing tool.  Your help is appreciated :)

**Comment by Uldiniad** [comment]
https://www.reddit.com/r/CalyxOS/comments/krp8qf/firefox_marks_deviceflasherexe_as_malware/gibzfjo/?utm_source=reddit&utm_medium=web2x&context=3
Should be fixed once https://github.com/AOSPAlliance/device-flasher/issues/4 is ready
