### ISSUE TITLE
Provide static binaries for Linux

### ISSUE THREAD

**Issue by ghost** [AOSPAlliance/device-flasher#5]
```
[norbert@magellan ~]$ ldd device-flasher.linux 
./device-flasher.linux: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./device-flasher.linux)
	linux-vdso.so.1 (0x00007ffd2437a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7f97a09000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7f9783f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7f97a48000)
```

This is on a Fedora 32 system, which comes with GLIBC 2.31, would be nice to have a static binary for Linux.

**Comment by chirayudesai** [comment]
I built this release on ArchLinux, which has the latest, hence the issue.

Static is an option, and another is just making a build on something older.

https://gitlab.com/CalyxOS/device-flasher/-/jobs/770699499/artifacts/file/device-flasher.linux is the GitLab CI build, which should work fine.

**Comment by chirayudesai** [comment]
https://github.com/AOSPAlliance/device-flasher/commit/4a196e9b0246508ef5f7d47949bf67cb55649671

Done, I'll make a new tag and put up some new binaries

**Comment by chirayudesai** [comment]
https://github.com/AOSPAlliance/device-flasher/releases/tag/1.0.2

Testing would be appreciated!
