### ISSUE TITLE
Tar support

### ISSUE THREAD

**Issue by chirayudesai** [AOSPAlliance/device-flasher#6]
* RattlesnakeOS uses .tar.xz
* Xiaomi stock uses .tgz

There must be some module/library that we can pull in to support these use-cases.

Size-wise it doesn't seem to make a difference, since the majority of the space is taken up by the zipfile inside the factory image, and that needs to be a zip for `fastboot update`

**Comment by Uldiniad** [comment]
https://review.calyxos.org/c/AOSPAlliance/device-flasher/+/232

**Comment by Uldiniad** [comment]
refactor deals with this
